# 注册中心服务端配置
spring:
  profiles: 
    active: dev
  
---
serve:
  port: 7001
# spring 配置
spring:
  profiles: dev
  application:
    name: springcloud-registry

# Eureka 配置
eureka:
  instance:
    hostname: localhost  # Eureka 服务端实例名字
  client:
    fetch-registry: false  # 自己是注册中心
    register-with-eureka: false # 不需要向注册中心注册自己
    service-url:  # 监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/

---
serve:
  port: 7001
# spring 配置
spring:
  profiles: test
  application:
    name: springcloud-registry

# Eureka 配置
eureka:
  client:
    fetch-registry: false  # 自己是注册中心
    register-with-eureka: false # 不需要向注册中心注册自己
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/