spring:
  profiles: dev
  
---
# spring 配置
spring:
  profiles: dev
  application:
    name: springcloud-config-clint

# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

---
# spring 配置
spring:
  profiles: test
  application:
    name: springcloud-config-clint

# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/