server:
  port: 8002

# mybatis 配置
mybatis:
  type-aliases-package: com.withered.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

# spring 配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddemo2?userUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC
    username: root
    password: 1234567

# eureka 配置
eureka:
  client:
    service-url:
      # 单机
      #defaultZone: http://localhost:7001/eureka/
      # 集群
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
      #defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-eureka-8002

# info 配置
info:
  app.name: withered-springcloud
  company.name: withered.com
