server:
  port: 8001

# mybatis 配置
mybatis:
  type-aliases-package: com.withered.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

# spring 配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddemo1?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC
    username: root
    password: 1234567
