server:
  port: 9527

# spring 配置
spring:
  application:
    name: springcloud-zuul-gateway

# Eureka 设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul-gateway-9527
    prefer-ip-address: true

info:
  app.name: springcloud-zuul-gateway
  company.name: withered.com

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*"  # 不能使用应用名访问，隐藏全部的应用名
  prefix: /withered  # 设置统一的访问前缀，要在9527后添加 /withered 才能访问
